from django.urls import path

from . import views
from .auth import staff_member_required


app_name = "comparator"

urlpatterns = [
    path("", staff_member_required(views.dashboard), name="dashboard"),
    path("stare/", staff_member_required(views.readiness), name="readiness"),
    path("rapoarte/saptamanal/", staff_member_required(views.weekly_report), name="weekly_report"),
    path("rapoarte/saptamanal/export/", staff_member_required(views.weekly_report_export), name="weekly_report_export"),
    path("calitate-potriviri/", staff_member_required(views.matching_quality), name="matching_quality"),
    path("furnizori/", staff_member_required(views.supplier_list), name="supplier_list"),
    path("furnizori/adauga/", staff_member_required(views.supplier_create), name="supplier_create"),
    path("furnizori/<int:pk>/parsare/", staff_member_required(views.supplier_parsing_profile), name="supplier_parsing_profile"),
    path("furnizori/liste-pret/importa/", staff_member_required(views.supplier_price_import_create), name="supplier_price_import_create"),
    path("furnizori/liste-pret/<int:pk>/", staff_member_required(views.supplier_price_import_detail), name="supplier_price_import_detail"),
    path("furnizori/liste-pret/<int:pk>/confirma/", staff_member_required(views.supplier_price_import_confirm), name="supplier_price_import_confirm"),
    path("catalog/", staff_member_required(views.product_list), name="product_list"),
    path("catalog/cauta/", staff_member_required(views.product_search), name="product_search"),
    path("catalog/<int:pk>/", staff_member_required(views.product_detail), name="product_detail"),
    path("catalog/export/<str:file_format>/", staff_member_required(views.catalog_export), name="catalog_export"),
    path("catalog/adauga/", staff_member_required(views.product_create), name="product_create"),
    path("catalog/scaneaza-ean/", staff_member_required(views.barcode_scanner), name="barcode_scanner"),
    path("catalog/ean/cauta/", staff_member_required(views.barcode_lookup), name="barcode_lookup"),
    path("catalog/ean/asociaza/", staff_member_required(views.barcode_assign), name="barcode_assign"),
    path("alerte/", staff_member_required(views.price_alert_list), name="price_alert_list"),
    path("alerte/<int:pk>/sterge/", staff_member_required(views.price_alert_delete), name="price_alert_delete"),
    path("notificari/", staff_member_required(views.notification_settings), name="notification_settings"),
    path("notificari/aboneaza/", staff_member_required(views.push_subscribe), name="push_subscribe"),
    path("notificari/dezaboneaza/", staff_member_required(views.push_unsubscribe), name="push_unsubscribe"),
    path("notificari/test/", staff_member_required(views.push_test), name="push_test"),
    path("cumparaturi/", staff_member_required(views.shopping_list_index), name="shopping_list_index"),
    path("cumparaturi/<int:pk>/", staff_member_required(views.shopping_list_detail), name="shopping_list_detail"),
    path("cumparaturi/<int:pk>/editeaza/", staff_member_required(views.shopping_list_edit), name="shopping_list_edit"),
    path("cumparaturi/articol/<int:pk>/bifeaza/", staff_member_required(views.shopping_list_item_toggle), name="shopping_list_item_toggle"),
    path("cumparaturi/articol/<int:pk>/sterge/", staff_member_required(views.shopping_list_item_delete), name="shopping_list_item_delete"),
    path("stoc/", staff_member_required(views.inventory_index), name="inventory_index"),
    path("stoc/vanzari/importa/", staff_member_required(views.sales_import_create), name="sales_import_create"),
    path("stoc/vanzari/<int:pk>/", staff_member_required(views.sales_import_detail), name="sales_import_detail"),
    path("stoc/vanzari/<int:pk>/aplica/", staff_member_required(views.sales_import_apply), name="sales_import_apply"),
    path("stoc/vanzari/linii/<int:pk>/editeaza/", staff_member_required(views.sales_import_line_edit), name="sales_import_line_edit"),
    path("marje/", staff_member_required(views.margin_analysis), name="margin_analysis"),
    path("stoc/reaprovizionare/", staff_member_required(views.inventory_replenishment_create), name="inventory_replenishment_create"),
    path("stoc/<int:pk>/editeaza/", staff_member_required(views.inventory_item_edit), name="inventory_item_edit"),
    path("stoc/<int:pk>/miscare/", staff_member_required(views.stock_movement_create), name="stock_movement_create"),
    path("metro/", staff_member_required(views.metro_list), name="metro_list"),
    path("metro/abateri/", staff_member_required(views.metro_price_anomalies), name="metro_price_anomalies"),
    path(
        "metro/abateri/<int:pk>/revizuieste/",
        staff_member_required(views.metro_price_anomaly_review),
        name="metro_price_anomaly_review",
    ),
    path("metro/adauga/", staff_member_required(views.metro_offer_create), name="metro_offer_create"),
    path("metro/importa/", staff_member_required(views.metro_import), name="metro_import"),
    path("metro/sincronizeaza-documente/", staff_member_required(views.metro_sync_documents), name="metro_sync_documents"),
    path("metro/scanari/", staff_member_required(views.metro_scrape_list), name="metro_scrape_list"),
    path("metro/scanari/porneste/", staff_member_required(views.metro_scrape_start), name="metro_scrape_start"),
    path("metro/scanari/catalog-complet/", staff_member_required(views.metro_scrape_mass_start), name="metro_scrape_mass_start"),
    path("metro/scanari/catalog-api/", staff_member_required(views.metro_scrape_api_start), name="metro_scrape_api_start"),
    path("metro/scanari/extindere-rapida/", staff_member_required(views.metro_scrape_breadth_start), name="metro_scrape_breadth_start"),
    path("metro/scanari/acoperire-alfabetica/", staff_member_required(views.metro_scrape_alphabet_start), name="metro_scrape_alphabet_start"),
    path("metro/scanari/sitemap/", staff_member_required(views.metro_sitemap_import), name="metro_sitemap_import"),
    path("metro/scanari/<int:pk>/", staff_member_required(views.metro_scrape_detail), name="metro_scrape_detail"),
    path("metro/scanari/<int:pk>/importa/", staff_member_required(views.metro_scrape_import), name="metro_scrape_import"),
    path("facturi/", staff_member_required(views.invoice_list), name="invoice_list"),
    path("facturi/inbox/", staff_member_required(views.document_inbox), name="document_inbox"),
    path("facturi/adauga/", staff_member_required(views.invoice_create), name="invoice_create"),
    path("facturi/<int:pk>/", staff_member_required(views.invoice_detail), name="invoice_detail"),
    path("facturi/<int:pk>/editeaza/", staff_member_required(views.invoice_edit), name="invoice_edit"),
    path("facturi/<int:pk>/sterge/", staff_member_required(views.invoice_delete), name="invoice_delete"),
    path("facturi/<int:pk>/fisier/", staff_member_required(views.invoice_file_download), name="invoice_file_download"),
    path("facturi/<int:pk>/pagini/adauga/", staff_member_required(views.invoice_pages_add), name="invoice_pages_add"),
    path("documente/pagini/<int:pk>/fisier/", staff_member_required(views.document_page_download), name="document_page_download"),
    path("documente/pagini/<int:pk>/muta/", staff_member_required(views.document_page_move), name="document_page_move"),
    path("documente/pagini/<int:pk>/sterge/", staff_member_required(views.document_page_delete), name="document_page_delete"),
    path("facturi/<int:pk>/proceseaza/", staff_member_required(views.invoice_process), name="invoice_process"),
    path(
        "facturi/<int:pk>/versiuni/<int:revision_pk>/restaureaza/",
        staff_member_required(views.invoice_revision_restore),
        name="invoice_revision_restore",
    ),
    path("facturi/<int:pk>/revizuieste/", staff_member_required(views.invoice_lines_review), name="invoice_lines_review"),
    path("facturi/<int:pk>/linie/adauga/", staff_member_required(views.line_create), name="line_create"),
    path("linii/<int:pk>/editeaza/", staff_member_required(views.line_edit), name="line_edit"),
    path("linii/<int:pk>/sterge/", staff_member_required(views.line_delete), name="line_delete"),
]
