# Generated by Django 5.2.16 on 2026-07-14 19:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=80, verbose_name='număr factură/bon')),
                ('issued_at', models.DateField(verbose_name='data documentului')),
                ('document', models.FileField(blank=True, upload_to='invoices/%Y/%m/', verbose_name='imagine sau PDF')),
                ('ocr_text', models.TextField(blank=True, verbose_name='text extras / introdus manual')),
                ('status', models.CharField(choices=[('NEW', 'Nouă'), ('PROCESSED', 'Procesată'), ('REVIEW', 'Necesită verificare'), ('ERROR', 'Eroare OCR')], default='NEW', max_length=12)),
                ('processing_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, verbose_name='observații')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'factură',
                'verbose_name_plural': 'facturi',
                'ordering': ['-issued_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True, verbose_name='denumire')),
                ('tax_id', models.CharField(blank=True, max_length=30, verbose_name='CUI')),
                ('notes', models.TextField(blank=True, verbose_name='observații')),
            ],
            options={
                'verbose_name': 'furnizor',
                'verbose_name_plural': 'furnizori',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='produs')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='marcă')),
                ('ean', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='EAN')),
                ('base_unit', models.CharField(choices=[('BUC', 'Bucată'), ('KG', 'Kilogram'), ('L', 'Litru')], max_length=3, verbose_name='unitate de bază')),
                ('active', models.BooleanField(default=True, verbose_name='activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'produs urmărit',
                'verbose_name_plural': 'produse urmărite',
                'ordering': ['name', 'brand'],
                'constraints': [models.UniqueConstraint(fields=('name', 'brand', 'base_unit'), name='unique_catalog_product')],
            },
        ),
        migrations.CreateModel(
            name='MetroOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_per_package', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='bucăți în pachet')),
                ('unit_size', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='cantitate per bucată')),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preț pachet cu TVA')),
                ('valid_from', models.DateField(verbose_name='valabil de la')),
                ('source', models.CharField(default='METRO', max_length=120, verbose_name='sursă')),
                ('active', models.BooleanField(default=True, verbose_name='ofertă activă')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metro_offers', to='comparator.product')),
            ],
            options={
                'verbose_name': 'preț METRO',
                'verbose_name_plural': 'prețuri METRO',
                'ordering': ['-valid_from', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=240, verbose_name='denumire de pe factură')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='număr pachete/bucăți')),
                ('units_per_package', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='bucăți în pachet')),
                ('unit_size', models.DecimalField(decimal_places=3, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='cantitate per bucată')),
                ('base_unit', models.CharField(choices=[('BUC', 'Bucată'), ('KG', 'Kilogram'), ('L', 'Litru')], default='BUC', max_length=3, verbose_name='unitate de bază')),
                ('unit_price_gross', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preț pachet/bucată cu TVA')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TVA %')),
                ('line_total_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='total linie cu TVA')),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('needs_review', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='comparator.invoice')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='comparator.product')),
            ],
            options={
                'verbose_name': 'linie factură',
                'verbose_name_plural': 'linii factură',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='comparator.supplier'),
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=220)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='comparator.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='comparator.supplier')),
            ],
            options={
                'ordering': ['alias'],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'alias'), name='unique_supplier_product_alias')],
            },
        ),
    ]
