# Generated by Django 5.2.16 on 2026-07-14 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-issued_at', '-created_at'], 'verbose_name': 'document de achiziție', 'verbose_name_plural': 'documente de achiziție'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Factură'), ('RECEIPT', 'Bon fiscal')], default='INVOICE', max_length=10, verbose_name='tip document'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='is_metro',
            field=models.BooleanField(default=False, help_text='Documentele confirmate de la acest furnizor actualizează prețurile METRO.', verbose_name='este METRO'),
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='imagine/PDF')),
                ('page_order', models.PositiveSmallIntegerField(default=1, verbose_name='ordine')),
                ('ocr_text', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='comparator.invoice')),
            ],
            options={
                'ordering': ['page_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('invoice', 'page_order'), name='unique_document_page_order')],
            },
        ),
    ]
