# Generated by Django 5.2.16 on 2026-07-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0002_alter_invoice_options_invoice_document_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetroScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('RUNNING', 'Browser deschis'), ('COMPLETED', 'Finalizat'), ('ERROR', 'Eroare')], default='PENDING', max_length=12)),
                ('start_url', models.URLField(max_length=500)),
                ('captured_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('current_url', models.URLField(blank=True, max_length=1000)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetroScrapedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, verbose_name='cod METRO')),
                ('name', models.CharField(max_length=240, verbose_name='denumire')),
                ('product_url', models.URLField(max_length=1000)),
                ('store_name', models.CharField(blank=True, max_length=120, verbose_name='magazin')),
                ('package_text', models.CharField(blank=True, max_length=120, verbose_name='ambalare afișată')),
                ('units_per_package', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('unit_size', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('base_unit', models.CharField(choices=[('BUC', 'Bucată'), ('KG', 'Kilogram'), ('L', 'Litru')], default='BUC', max_length=3)),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preț cu TVA')),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('imported', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now=True)),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metro_scrape_rows', to='comparator.product')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='comparator.metroscrapejob')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('job', 'external_id'), name='unique_scraped_product_per_job')],
            },
        ),
    ]
