# Generated by Django 5.2.16 on 2026-07-14 20:37

import comparator.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0003_metroscrapejob_metroscrapedproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpage',
            name='file',
            field=models.FileField(upload_to='documents/%Y/%m/', validators=[comparator.validators.validate_document_upload], verbose_name='imagine/PDF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='document',
            field=models.FileField(blank=True, upload_to='invoices/%Y/%m/', validators=[comparator.validators.validate_document_upload], verbose_name='imagine sau PDF'),
        ),
    ]
