# Generated by Django 5.2.16 on 2026-07-14 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0004_alter_documentpage_file_alter_invoice_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroscrapedproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Lactate', 'Lactate'), ('Băuturi nealcoolice', 'Băuturi nealcoolice'), ('Băuturi alcoolice', 'Băuturi alcoolice'), ('Fructe și legume', 'Fructe și legume'), ('Băcănie', 'Băcănie'), ('Ouă', 'Ouă'), ('Conserve și pate', 'Conserve și pate'), ('Mezeluri', 'Mezeluri'), ('Dulciuri', 'Dulciuri'), ('Snacks', 'Snacks'), ('Igienă personală', 'Igienă personală'), ('Curățenie', 'Curățenie'), ('Cafea și ceai', 'Cafea și ceai'), ('Sosuri și condimente', 'Sosuri și condimente'), ('Panificație', 'Panificație'), ('Congelate', 'Congelate'), ('Altele', 'Altele')], db_index=True, max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Lactate', 'Lactate'), ('Băuturi nealcoolice', 'Băuturi nealcoolice'), ('Băuturi alcoolice', 'Băuturi alcoolice'), ('Fructe și legume', 'Fructe și legume'), ('Băcănie', 'Băcănie'), ('Ouă', 'Ouă'), ('Conserve și pate', 'Conserve și pate'), ('Mezeluri', 'Mezeluri'), ('Dulciuri', 'Dulciuri'), ('Snacks', 'Snacks'), ('Igienă personală', 'Igienă personală'), ('Curățenie', 'Curățenie'), ('Cafea și ceai', 'Cafea și ceai'), ('Sosuri și condimente', 'Sosuri și condimente'), ('Panificație', 'Panificație'), ('Congelate', 'Congelate'), ('Altele', 'Altele')], db_index=True, max_length=80, verbose_name='categorie'),
        ),
    ]
