# Generated by Django 5.2.16 on 2026-08-08 12:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_codes_and_supplier_history(apps, schema_editor):
    Product = apps.get_model("comparator", "Product")
    ProductCode = apps.get_model("comparator", "ProductCode")
    MetroScrapedProduct = apps.get_model("comparator", "MetroScrapedProduct")
    InvoiceLine = apps.get_model("comparator", "InvoiceLine")
    SupplierOffer = apps.get_model("comparator", "SupplierOffer")

    for product in Product.objects.exclude(ean="").iterator():
        ProductCode.objects.get_or_create(
            kind="EAN", code=product.ean.strip().upper(), supplier=None, defaults={"product": product}
        )
    rows = MetroScrapedProduct.objects.filter(imported=True, matched_product__isnull=False)
    for row in rows.iterator():
        ProductCode.objects.get_or_create(
            kind="METRO", code=row.external_id, supplier=None,
            defaults={"product_id": row.matched_product_id},
        )
    confirmed = InvoiceLine.objects.filter(needs_review=False, matched_product__isnull=False).select_related("invoice")
    for line in confirmed.iterator():
        total_base = line.quantity * line.units_per_package * line.unit_size
        gross = line.line_total_gross
        if gross is None:
            gross = line.quantity * line.unit_price_gross
        gross = max(gross - line.discount_gross - line.deposit_gross, Decimal("0"))
        if total_base:
            SupplierOffer.objects.get_or_create(
                invoice_line_id=line.pk,
                defaults={
                    "supplier_id": line.invoice.supplier_id,
                    "product_id": line.matched_product_id,
                    "price_per_base_unit": gross / total_base,
                    "base_unit": line.base_unit,
                    "valid_from": line.invoice.issued_at,
                },
            )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0005_metroscrapedproduct_category_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_discount_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='reducere document'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transport_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='transport cu TVA'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='deposit_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='SGR/garanție'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='discount_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='reducere linie'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='ean',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='EAN / cod produs'),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='completed_queries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='store_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='total_queries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='prag lei/unitate')),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='comparator.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='MetroScrapeTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=160)),
                ('category', models.CharField(blank=True, choices=[('Lactate', 'Lactate'), ('Băuturi nealcoolice', 'Băuturi nealcoolice'), ('Băuturi alcoolice', 'Băuturi alcoolice'), ('Fructe și legume', 'Fructe și legume'), ('Băcănie', 'Băcănie'), ('Ouă', 'Ouă'), ('Conserve și pate', 'Conserve și pate'), ('Mezeluri', 'Mezeluri'), ('Dulciuri', 'Dulciuri'), ('Snacks', 'Snacks'), ('Igienă personală', 'Igienă personală'), ('Curățenie', 'Curățenie'), ('Cafea și ceai', 'Cafea și ceai'), ('Sosuri și condimente', 'Sosuri și condimente'), ('Panificație', 'Panificație'), ('Congelate', 'Congelate'), ('Altele', 'Altele')], max_length=80)),
                ('status', models.CharField(choices=[('PENDING', 'În așteptare'), ('RUNNING', 'În curs'), ('COMPLETED', 'Finalizat'), ('ERROR', 'Eroare')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('found_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='comparator.metroscrapejob')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('job', 'term'), name='unique_term_per_metro_job')],
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EAN', 'EAN / cod de bare'), ('METRO', 'Cod METRO'), ('SUPPLIER', 'Cod furnizor')], max_length=12)),
                ('code', models.CharField(db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='comparator.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_codes', to='comparator.supplier')),
            ],
            options={
                'ordering': ['kind', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('supplier__isnull', True)), fields=('kind', 'code'), name='unique_global_product_code'), models.UniqueConstraint(condition=models.Q(('supplier__isnull', False)), fields=('supplier', 'kind', 'code'), name='unique_supplier_product_code')],
            },
        ),
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='cantitate necesară')),
                ('purchased', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_items', to='comparator.product')),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='comparator.shoppinglist')),
            ],
            options={
                'ordering': ['product__name'],
                'constraints': [models.UniqueConstraint(fields=('shopping_list', 'product'), name='unique_product_per_shopping_list')],
            },
        ),
        migrations.CreateModel(
            name='SupplierOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_base_unit', models.DecimalField(decimal_places=4, max_digits=14)),
                ('base_unit', models.CharField(choices=[('BUC', 'Bucată'), ('KG', 'Kilogram'), ('L', 'Litru')], max_length=3)),
                ('valid_from', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offer', to='comparator.invoiceline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_offers', to='comparator.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='comparator.supplier')),
            ],
            options={
                'ordering': ['-valid_from', 'price_per_base_unit'],
                'indexes': [models.Index(fields=['product', 'supplier', '-valid_from'], name='comparator__product_646ae5_idx')],
            },
        ),
        migrations.RunPython(seed_codes_and_supplier_history, noop_reverse),
    ]
