# Generated by Django 5.2.16 on 2026-08-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0007_alter_metroscrapedproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrooffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
