# Generated by Django 5.2.16 on 2026-08-09 17:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0009_pricealert_last_notified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_total_gross',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Totalul final tipărit pe factură sau bon, folosit pentru verificare.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='total document cu TVA'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_total_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='total linie cu TVA'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='TVA %'),
        ),
    ]
