# Generated by Django 5.2.16 on 2026-08-09 17:07

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0010_document_reconciliation'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('number'), models.F('supplier'), models.F('issued_at'), condition=models.Q(('number', ''), _negated=True), name='unique_supplier_document_number_date'),
        ),
    ]
