# Generated by Django 5.2.16 on 2026-08-09 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0011_prevent_duplicate_documents'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('OCR_REPROCESS', 'Înainte de reprocesare OCR'), ('RESTORE', 'Înainte de restaurarea altei versiuni')], max_length=20)),
                ('snapshot', models.JSONField()),
                ('line_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_revisions', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='comparator.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
