# Generated by Django 5.2.16 on 2026-08-25 16:09

import django.db.models.deletion
from django.db import migrations, models


def backfill_metro_product_states(apps, schema_editor):
    ScrapedProduct = apps.get_model("comparator", "MetroScrapedProduct")
    ProductState = apps.get_model("comparator", "MetroProductState")
    states = {}
    rows = ScrapedProduct.objects.filter(
        imported=True,
        matched_product_id__isnull=False,
    ).select_related("job").order_by("captured_at", "id")
    for row in rows.iterator(chunk_size=500):
        store_name = (row.store_name or row.job.store_name or "METRO").strip()[:120]
        key = (store_name, row.external_id)
        existing = states.get(key)
        if existing is None:
            states[key] = ProductState(
                product_id=row.matched_product_id,
                external_id=row.external_id,
                store_name=store_name,
                first_seen_at=row.captured_at,
                last_seen_at=row.captured_at,
                first_seen_job_id=row.job_id,
                last_seen_job_id=row.job_id,
                last_price_gross=row.price_gross,
                last_units_per_package=row.units_per_package,
                last_unit_size=row.unit_size,
                last_base_unit=row.base_unit,
                last_package_text=row.package_text,
            )
            continue
        existing.product_id = row.matched_product_id
        existing.last_seen_at = row.captured_at
        existing.last_seen_job_id = row.job_id
        existing.last_price_gross = row.price_gross
        existing.last_units_per_package = row.units_per_package
        existing.last_unit_size = row.unit_size
        existing.last_base_unit = row.base_unit
        existing.last_package_text = row.package_text
    ProductState.objects.bulk_create(states.values(), batch_size=500)


def clear_metro_product_states(apps, schema_editor):
    apps.get_model("comparator", "MetroProductState").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0012_invoice_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroscrapejob',
            name='lifecycle_finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='missing_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='new_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='reactivated_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='unavailable_products_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MetroProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=80, verbose_name='cod METRO')),
                ('store_name', models.CharField(db_index=True, max_length=120, verbose_name='magazin')),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('consecutive_misses', models.PositiveSmallIntegerField(default=0)),
                ('available', models.BooleanField(db_index=True, default=True)),
                ('last_price_gross', models.DecimalField(decimal_places=2, max_digits=12)),
                ('last_units_per_package', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('last_unit_size', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('last_base_unit', models.CharField(choices=[('BUC', 'Bucată'), ('KG', 'Kilogram'), ('L', 'Litru')], default='BUC', max_length=3)),
                ('last_package_text', models.CharField(blank=True, max_length=120)),
                ('first_seen_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_seen_states', to='comparator.metroscrapejob')),
                ('last_seen_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_seen_states', to='comparator.metroscrapejob')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metro_states', to='comparator.product')),
                ('reactivated_in_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactivated_states', to='comparator.metroscrapejob')),
            ],
            options={
                'ordering': ['store_name', 'product__name'],
                'indexes': [models.Index(fields=['store_name', 'available', 'last_seen_at'], name='comparator__store_n_bffcb7_idx')],
                'constraints': [models.UniqueConstraint(fields=('store_name', 'external_id'), name='unique_metro_product_state_per_store')],
            },
        ),
        migrations.RunPython(backfill_metro_product_states, clear_metro_product_states),
    ]
