# Generated by Django 5.2.16 on 2026-08-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0013_metro_product_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroscrapejob',
            name='package_changes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metroscrapejob',
            name='price_changes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
