# Generated by Django 5.2.16 on 2026-08-25 16:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0014_metro_change_counters'),
    ]

    operations = [
        migrations.AddField(
            model_name='metroproductstate',
            name='last_volume_prices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='metroscrapedproduct',
            name='volume_prices',
            field=models.JSONField(blank=True, default=list, verbose_name='praguri de volum'),
        ),
        migrations.CreateModel(
            name='MetroOfferTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_packages', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)], verbose_name='de la pachete')),
                ('price_gross', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='preț pachet cu TVA')),
                ('label', models.CharField(blank=True, max_length=120, verbose_name='text METRO')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_tiers', to='comparator.metrooffer')),
            ],
            options={
                'verbose_name': 'prag de volum METRO',
                'verbose_name_plural': 'praguri de volum METRO',
                'ordering': ['min_packages'],
                'constraints': [models.UniqueConstraint(fields=('offer', 'min_packages'), name='unique_metro_volume_tier')],
            },
        ),
    ]
