# Generated by Django 5.2.17 on 2026-08-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0015_metro_volume_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='match_candidates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='match_corrected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='match_gap',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='match_method',
            field=models.CharField(choices=[('NONE', 'Fără potrivire'), ('CODE', 'Cod exact'), ('ALIAS', 'Alias învățat'), ('FUZZY', 'Denumire și gramaj'), ('MANUAL', 'Confirmare manuală')], default='NONE', max_length=10),
        ),
    ]
