# Generated by Django 5.2.17 on 2026-08-25 17:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0016_matching_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='receive_into_stock',
            field=models.BooleanField(default=False, help_text='Bifează numai pentru achiziții care trebuie adăugate la stocul curent.', verbose_name='recepționează în stoc'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='stoc minim')),
                ('target_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='stoc țintă')),
                ('shelf_life_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='valabilitate orientativă în zile')),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='comparator.product')),
            ],
            options={
                'ordering': ['product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=14, verbose_name='modificare cantitate')),
                ('reason', models.CharField(choices=[('OPENING', 'Stoc inițial'), ('RECEIPT', 'Recepție document'), ('SALE', 'Vânzare'), ('WASTE', 'Pierdere / expirare'), ('ADJUSTMENT', 'Ajustare inventar')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=240, verbose_name='explicație')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='comparator.inventoryitem')),
                ('invoice_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movement', to='comparator.invoiceline')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('target_quantity__gte', models.F('minimum_quantity'))), name='inventory_target_at_least_minimum'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='stock_movement_nonzero'),
        ),
    ]
