# Generated by Django 5.2.17 on 2026-08-25 21:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0017_inventory_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='budget_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='buget cu TVA'),
        ),
        migrations.AddField(
            model_name='shoppinglistitem',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Urgent'), (2, 'Normal'), (3, 'Poate aștepta')], default=2, verbose_name='prioritate'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='free_transport_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='transport gratuit de la'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='comandă minimă cu TVA'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='transport_gross',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='transport standard cu TVA'),
        ),
    ]
