# Generated by Django 5.2.17 on 2026-08-26

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparator", "0018_procurement_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="expected_waste_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("99.99")),
                ],
                verbose_name="pierderi estimate %",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="purchase_vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Folosit pentru calculul marjei nete; verifică valoarea din factura furnizorului.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="TVA achiziție %",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="retail_price_gross",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Prețul unei unități vândute la raft.",
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                verbose_name="preț vânzare cu TVA",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="retail_unit_size",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                help_text="De exemplu 2 pentru o sticlă de 2 L sau 0,4 pentru 400 g.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
                verbose_name="cantitate de bază per unitate vândută",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="retail_vat_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
                verbose_name="TVA vânzare %",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="target_margin_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("99.99")),
                ],
                verbose_name="marjă țintă %",
            ),
        ),
    ]
