# Generated by Django 5.2.17 on 2026-08-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparator", "0019_inventory_retail_margin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="metroscrapejob",
            name="scan_type",
            field=models.CharField(
                choices=[("MANUAL", "Manuală"), ("TARGETED", "Catalog urmărit"), ("FULL", "Catalog complet")],
                db_index=True,
                default="MANUAL",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("MAINTENANCE", "Mentenanță zilnică")], default="MAINTENANCE", max_length=20)),
                ("status", models.CharField(choices=[("RUNNING", "În curs"), ("COMPLETED", "Finalizată"), ("ERROR", "Eroare")], default="RUNNING", max_length=12)),
                ("summary", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("metro_job", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="automation_runs", to="comparator.metroscrapejob")),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="MetroPriceAnomaly",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("old_price_per_base", models.DecimalField(decimal_places=4, max_digits=14)),
                ("new_price_per_base", models.DecimalField(decimal_places=4, max_digits=14)),
                ("change_percent", models.DecimalField(decimal_places=2, max_digits=9)),
                ("status", models.CharField(choices=[("OPEN", "De verificat"), ("CONFIRMED", "Confirmată"), ("DISMISSED", "Ignorată")], db_index=True, default="OPEN", max_length=10)),
                ("note", models.CharField(blank=True, max_length=300)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("job", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="price_anomalies", to="comparator.metroscrapejob")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="metro_price_anomalies", to="comparator.product")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_metro_price_anomalies", to=settings.AUTH_USER_MODEL)),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="price_anomalies", to="comparator.metroproductstate")),
            ],
            options={
                "ordering": ["-detected_at"],
                "constraints": [models.UniqueConstraint(fields=("state", "job"), name="unique_metro_price_anomaly_per_job")],
            },
        ),
    ]
