# Generated by Django 5.2.17 on 2026-08-26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparator", "0021_classify_existing_full_scans"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentProcessingJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "În așteptare"), ("RUNNING", "Se procesează"), ("COMPLETED", "Finalizat"), ("ERROR", "Eroare")], db_index=True, default="PENDING", max_length=12)),
                ("force_ocr", models.BooleanField(default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="processing_jobs", to="comparator.invoice")),
                ("requested_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="document_processing_jobs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["status", "created_at"], name="comparator__status_66c058_idx")],
                "constraints": [models.UniqueConstraint(condition=models.Q(("status__in", ["PENDING", "RUNNING"])), fields=("invoice",), name="unique_active_document_processing_job")],
            },
        ),
    ]
