# Generated by Django 5.2.17 on 2026-08-26 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0022_document_processing_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpage',
            name='ocr_quality_score',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='calitate OCR'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='ocr_strategy',
            field=models.CharField(blank=True, max_length=20, verbose_name='strategie OCR'),
        ),
        migrations.AddField(
            model_name='documentpage',
            name='ocr_warnings',
            field=models.JSONField(blank=True, default=list, verbose_name='avertismente OCR'),
        ),
    ]
