# Generated by Django 5.2.17 on 2026-08-26 15:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0023_document_ocr_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierParsingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_mode', models.CharField(choices=[('AUTO', 'Automat (recomandat)'), ('HEURISTIC', 'Doar reguli locale'), ('OLLAMA', 'Preferă Ollama local')], default='AUTO', max_length=12)),
                ('apply_default_vat', models.BooleanField(default=False, help_text='Se aplică doar liniilor unde documentul nu conține o cotă TVA.', verbose_name='completează TVA implicit')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='TVA implicit (%)')),
                ('documents_processed', models.PositiveIntegerField(default=0)),
                ('extracted_lines', models.PositiveIntegerField(default=0)),
                ('confirmed_lines', models.PositiveIntegerField(default=0)),
                ('corrected_lines', models.PositiveIntegerField(default=0)),
                ('average_match_score', models.PositiveSmallIntegerField(default=0)),
                ('last_parser', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsing_profile', to='comparator.supplier')),
            ],
            options={
                'ordering': ['supplier__name'],
            },
        ),
    ]
