# Generated by Django 5.2.17 on 2026-08-26 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0024_supplier_parsing_profiles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('INVOICE', 'Factură'), ('RECEIPT', 'Bon fiscal'), ('PRICE_LIST', 'Listă de preț')], default='INVOICE', max_length=10, verbose_name='tip document'),
        ),
        migrations.CreateModel(
            name='SupplierPriceImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_at', models.DateField(verbose_name='valabilă la')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Previzualizare'), ('IMPORTED', 'Importată'), ('ERROR', 'Eroare')], default='DRAFT', max_length=10)),
                ('rows', models.JSONField(default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_price_imports', to=settings.AUTH_USER_MODEL)),
                ('imported_invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_import', to='comparator.invoice')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_imports', to='comparator.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
