# Generated by Django 5.2.17 on 2026-08-26 15:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0025_supplier_price_list_imports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='source_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='SalesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Previzualizare'), ('PARTIAL', 'Aplicat parțial'), ('APPLIED', 'Aplicat')], default='DRAFT', max_length=10)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesImportLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('source_key', models.CharField(db_index=True, max_length=64)),
                ('external_reference', models.CharField(blank=True, max_length=120)),
                ('sold_at', models.DateTimeField()),
                ('original_name', models.CharField(blank=True, max_length=240)),
                ('ean', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('match_score', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('ignored', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_import_lines', to='comparator.product')),
                ('sales_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='comparator.salesimport')),
            ],
            options={
                'ordering': ['row_number'],
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sale_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movement', to='comparator.salesimportline'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key', ''), _negated=True), fields=('source_key',), name='unique_stock_movement_source_key'),
        ),
        migrations.AddConstraint(
            model_name='salesimportline',
            constraint=models.UniqueConstraint(fields=('sales_import', 'row_number'), name='unique_sales_import_row'),
        ),
    ]
