# Generated by Django 5.2.17 on 2026-08-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0026_pos_sales_imports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metroscrapedproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Lactate', 'Lactate'), ('Băuturi nealcoolice', 'Băuturi nealcoolice'), ('Băuturi alcoolice', 'Băuturi alcoolice'), ('Fructe și legume', 'Fructe și legume'), ('Băcănie', 'Băcănie'), ('Ouă', 'Ouă'), ('Conserve și pate', 'Conserve și pate'), ('Mezeluri', 'Mezeluri'), ('Dulciuri', 'Dulciuri'), ('Snacks', 'Snacks'), ('Igienă personală', 'Igienă personală'), ('Curățenie', 'Curățenie'), ('Cafea și ceai', 'Cafea și ceai'), ('Sosuri și condimente', 'Sosuri și condimente'), ('Panificație', 'Panificație'), ('Congelate', 'Congelate'), ('Carne și pește', 'Carne și pește'), ('Produse pentru copii', 'Produse pentru copii'), ('Hrană animale', 'Hrană animale'), ('Menaj și consumabile', 'Menaj și consumabile'), ('Semipreparate', 'Semipreparate'), ('Produse dietetice', 'Produse dietetice'), ('Papetărie și birou', 'Papetărie și birou'), ('Bucătărie și veselă', 'Bucătărie și veselă'), ('Altele', 'Altele')], db_index=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='metroscrapeterm',
            name='category',
            field=models.CharField(blank=True, choices=[('Lactate', 'Lactate'), ('Băuturi nealcoolice', 'Băuturi nealcoolice'), ('Băuturi alcoolice', 'Băuturi alcoolice'), ('Fructe și legume', 'Fructe și legume'), ('Băcănie', 'Băcănie'), ('Ouă', 'Ouă'), ('Conserve și pate', 'Conserve și pate'), ('Mezeluri', 'Mezeluri'), ('Dulciuri', 'Dulciuri'), ('Snacks', 'Snacks'), ('Igienă personală', 'Igienă personală'), ('Curățenie', 'Curățenie'), ('Cafea și ceai', 'Cafea și ceai'), ('Sosuri și condimente', 'Sosuri și condimente'), ('Panificație', 'Panificație'), ('Congelate', 'Congelate'), ('Carne și pește', 'Carne și pește'), ('Produse pentru copii', 'Produse pentru copii'), ('Hrană animale', 'Hrană animale'), ('Menaj și consumabile', 'Menaj și consumabile'), ('Semipreparate', 'Semipreparate'), ('Produse dietetice', 'Produse dietetice'), ('Papetărie și birou', 'Papetărie și birou'), ('Bucătărie și veselă', 'Bucătărie și veselă'), ('Altele', 'Altele')], max_length=80),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Lactate', 'Lactate'), ('Băuturi nealcoolice', 'Băuturi nealcoolice'), ('Băuturi alcoolice', 'Băuturi alcoolice'), ('Fructe și legume', 'Fructe și legume'), ('Băcănie', 'Băcănie'), ('Ouă', 'Ouă'), ('Conserve și pate', 'Conserve și pate'), ('Mezeluri', 'Mezeluri'), ('Dulciuri', 'Dulciuri'), ('Snacks', 'Snacks'), ('Igienă personală', 'Igienă personală'), ('Curățenie', 'Curățenie'), ('Cafea și ceai', 'Cafea și ceai'), ('Sosuri și condimente', 'Sosuri și condimente'), ('Panificație', 'Panificație'), ('Congelate', 'Congelate'), ('Carne și pește', 'Carne și pește'), ('Produse pentru copii', 'Produse pentru copii'), ('Hrană animale', 'Hrană animale'), ('Menaj și consumabile', 'Menaj și consumabile'), ('Semipreparate', 'Semipreparate'), ('Produse dietetice', 'Produse dietetice'), ('Papetărie și birou', 'Papetărie și birou'), ('Bucătărie și veselă', 'Bucătărie și veselă'), ('Altele', 'Altele')], db_index=True, max_length=80, verbose_name='categorie'),
        ),
    ]
