# Generated by Django 5.2.17 on 2026-08-31 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0027_expand_catalog_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=500)),
                ('view_name', models.CharField(blank=True, max_length=180)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Reușită'), ('DENIED', 'Refuzată'), ('ERROR', 'Eroare')], db_index=True, max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricematch_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'eveniment activitate',
                'verbose_name_plural': 'jurnal activitate',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='comparator__user_id_61a7ec_idx')],
            },
        ),
    ]
