# Generated by Django 5.2.17 on 2026-08-31 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0030_initial_data_import'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['outcome', '-created_at'], name='activity_outcome_time'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-issued_at', '-created_at'], name='invoice_recent'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', '-issued_at'], name='invoice_status_date'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['document_type', '-issued_at'], name='invoice_type_date'),
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['needs_review', 'matched_product'], name='line_review_match'),
        ),
        migrations.AddIndex(
            model_name='metrooffer',
            index=models.Index(fields=['product', 'source', 'active', '-valid_from'], name='metro_product_source_date'),
        ),
        migrations.AddIndex(
            model_name='metroscrapejob',
            index=models.Index(fields=['status', '-created_at'], name='metro_job_status_date'),
        ),
    ]
