# Generated by Django 5.2.17 on 2026-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comparator', '0031_activitylog_activity_outcome_time_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 0), ('retail_price_gross__gte', 0), ('retail_unit_size__gt', 0), ('target_quantity__gte', 0)), name='inventory_valid_quantities'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('purchase_vat_rate__gte', 0), ('purchase_vat_rate__lte', 100), ('retail_vat_rate__gte', 0), ('retail_vat_rate__lte', 100)), name='inventory_valid_vat_rates'),
        ),
        migrations.AddConstraint(
            model_name='inventoryitem',
            constraint=models.CheckConstraint(condition=models.Q(('expected_waste_percent__gte', 0), ('expected_waste_percent__lt', 100), ('target_margin_percent__gte', 0), ('target_margin_percent__lt', 100)), name='inventory_valid_percentages'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('document_discount_gross__gte', 0), ('document_total_gross__gte', 0), ('transport_gross__gte', 0)), name='invoice_nonnegative_totals'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('unit_size__gt', 0), ('units_per_package__gt', 0)), name='invoice_line_positive_units'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('deposit_gross__gte', 0), ('discount_gross__gte', 0), ('line_total_gross__gte', 0), ('unit_price_gross__gte', 0)), name='invoice_line_nonnegative_money'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('match_gap__lte', 100), ('match_score__lte', 100), ('vat_rate__gte', 0), ('vat_rate__lte', 100)), name='invoice_line_valid_scores'),
        ),
        migrations.AddConstraint(
            model_name='metrooffer',
            constraint=models.CheckConstraint(condition=models.Q(('price_gross__gte', 0), ('unit_size__gt', 0), ('units_per_package__gt', 0)), name='metro_offer_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='metrooffertier',
            constraint=models.CheckConstraint(condition=models.Q(('min_packages__gte', 2), ('price_gross__gte', 0)), name='metro_tier_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='pricealert',
            constraint=models.CheckConstraint(condition=models.Q(('last_notified_price__gte', 0), ('target_price__gte', 0)), name='price_alert_nonnegative_values'),
        ),
        migrations.AddConstraint(
            model_name='salesimportline',
            constraint=models.CheckConstraint(condition=models.Q(('match_score__lte', 100), ('quantity__gt', 0)), name='sales_line_valid_values'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglist',
            constraint=models.CheckConstraint(condition=models.Q(('budget_gross__gte', 0)), name='shopping_list_nonnegative_budget'),
        ),
        migrations.AddConstraint(
            model_name='shoppinglistitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='shopping_item_positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='supplieroffer',
            constraint=models.CheckConstraint(condition=models.Q(('price_per_base_unit__gte', 0)), name='supplier_offer_nonnegative_price'),
        ),
    ]
